use role ACCOUNTADMIN;
use schema GENOME1K;

---To create share "1KGENOMES" with relevant tables and views

CREATE SHARE "1KGENOMES" COMMENT='1000 Genomes Project Data and SNP, CLINVAR annotations';
GRANT USAGE ON DATABASE "GENOME" TO SHARE "1KGENOMES";
GRANT USAGE ON SCHEMA "GENOME"."GENOME1K" TO SHARE "1KGENOMES";
GRANT SELECT ON TABLE "GENOME"."GENOME1K"."CLINVAR" TO SHARE "1KGENOMES";
GRANT SELECT ON TABLE "GENOME"."GENOME1K"."GENOTYPES" TO SHARE "1KGENOMES";
GRANT SELECT ON VIEW "GENOME"."GENOME1K"."GENOTYPES_BY_SAMPLE" TO SHARE "1KGENOMES";
GRANT SELECT ON TABLE "GENOME"."GENOME1K"."HEADERS" TO SHARE "1KGENOMES";
GRANT SELECT ON TABLE "GENOME"."GENOME1K"."PANEL" TO SHARE "1KGENOMES";
GRANT SELECT ON TABLE "GENOME"."GENOME1K"."SNP" TO SHARE "1KGENOMES";
GRANT SELECT ON TABLE "GENOME"."GENOME1K"."VARIANTS" TO SHARE "1KGENOMES";
GRANT SELECT ON VIEW "GENOME"."GENOME1K"."VARIANTS_FLATTENED" TO SHARE "1KGENOMES";


----To add UDFs to "1KGENOMES" share
GRANT USAGE ON FUNCTION allele1(varchar, variant, varchar)
to share "1KGENOMES";
GRANT USAGE ON FUNCTION allele2(varchar, variant, varchar)
to share "1KGENOMES";
GRANT USAGE ON FUNCTION  allele_position(varchar, int)
to share "1KGENOMES";
GRANT USAGE ON FUNCTION  is_homozygous(varchar)
to share "1KGENOMES";
GRANT USAGE ON FUNCTION  allele_contained_in(varchar, variant, varchar, variant)
to share "1KGENOMES";
GRANT USAGE ON FUNCTION  allele_matches(varchar, variant, varchar, varchar)
to share "1KGENOMES";
GRANT USAGE ON FUNCTION  allele_count(varchar)
to share "1KGENOMES";
GRANT USAGE ON FUNCTION  matching_allele_count(varchar, varchar, variant, varchar)
to share "1KGENOMES";

----To share with specific account name
ALTER SHARE "1KGENOMES" ADD ACCOUNTS = ***AccountName***;
